title: Jiayun Kang's Homepage
page-top-title: Jiayun (Lucy) Kang
top-section-bg-text: Bioinformatics + Computer Science
home-subtitle: Jiayun Kang&ensp;|&ensp;康嘉昀
copyright-text: '&copy; Jiayun Kang 2023-2025. All Rights Reserved.'
